# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09cd6104b793c3f0aa5179ffc5c2eaa4252dff36ddbdea1d0b15457b4160ce8a3407f55378d12851b24fbe3cf335d2d115d3ea26d96f9f95ecb94053955c1d96

test:
  secret_key_base: 5cc63bdf590e7b6a3c8d76958a9786e354b1a9d6a7ef7d70f7495f761a859c37431d434b740d3bf107735e7fe03027538f52f93c0f585484d13d7c3071c5aa13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
